id: I9926222D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:21:02+00:00'
last_modified: '2022-06-08T17:35:23.489534+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17395
  title: 'པཎ་ཆེན་སྐུ་ཕྲེང་ལྔ་པ་བློ་བཟང་ཡེ་ཤེས་ཀྱི་རྣམ་ཐར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    66D3:
      image_group_id: I4PD2967
      title: ''
      total_pages: 430
      order: 1
      base_file: 66D3.txt
    0CA8:
      image_group_id: I4PD2968
      title: ''
      total_pages: 462
      order: 2
      base_file: 0CA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
